/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProfilesRouteImport } from './routes/app.profiles'
import { Route as AppCreateRouteImport } from './routes/app.create'
import { Route as AppCardsRouteImport } from './routes/app.cards'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as UHandleTypeRouteImport } from './routes/u.$handle.$type'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilesRoute = AppProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppCardsRoute = AppCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const UHandleTypeRoute = UHandleTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => UHandleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/cards': typeof AppCardsRoute
  '/app/create': typeof AppCreateRoute
  '/app/profiles': typeof AppProfilesRoute
  '/app/settings': typeof AppSettingsRoute
  '/u/$handle': typeof UHandleRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/u/$handle/$type': typeof UHandleTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/cards': typeof AppCardsRoute
  '/app/create': typeof AppCreateRoute
  '/app/profiles': typeof AppProfilesRoute
  '/app/settings': typeof AppSettingsRoute
  '/u/$handle': typeof UHandleRouteWithChildren
  '/app': typeof AppIndexRoute
  '/u/$handle/$type': typeof UHandleTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/cards': typeof AppCardsRoute
  '/app/create': typeof AppCreateRoute
  '/app/profiles': typeof AppProfilesRoute
  '/app/settings': typeof AppSettingsRoute
  '/u/$handle': typeof UHandleRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/u/$handle/$type': typeof UHandleTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/analytics'
    | '/app/billing'
    | '/app/cards'
    | '/app/create'
    | '/app/profiles'
    | '/app/settings'
    | '/u/$handle'
    | '/app/'
    | '/u/$handle/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/analytics'
    | '/app/billing'
    | '/app/cards'
    | '/app/create'
    | '/app/profiles'
    | '/app/settings'
    | '/u/$handle'
    | '/app'
    | '/u/$handle/$type'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/analytics'
    | '/app/billing'
    | '/app/cards'
    | '/app/create'
    | '/app/profiles'
    | '/app/settings'
    | '/u/$handle'
    | '/app/'
    | '/u/$handle/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  UHandleRoute: typeof UHandleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profiles': {
      id: '/app/profiles'
      path: '/profiles'
      fullPath: '/app/profiles'
      preLoaderRoute: typeof AppProfilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/create': {
      id: '/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cards': {
      id: '/app/cards'
      path: '/cards'
      fullPath: '/app/cards'
      preLoaderRoute: typeof AppCardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/u/$handle/$type': {
      id: '/u/$handle/$type'
      path: '/$type'
      fullPath: '/u/$handle/$type'
      preLoaderRoute: typeof UHandleTypeRouteImport
      parentRoute: typeof UHandleRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCardsRoute: typeof AppCardsRoute
  AppCreateRoute: typeof AppCreateRoute
  AppProfilesRoute: typeof AppProfilesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBillingRoute: AppBillingRoute,
  AppCardsRoute: AppCardsRoute,
  AppCreateRoute: AppCreateRoute,
  AppProfilesRoute: AppProfilesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface UHandleRouteChildren {
  UHandleTypeRoute: typeof UHandleTypeRoute
}

const UHandleRouteChildren: UHandleRouteChildren = {
  UHandleTypeRoute: UHandleTypeRoute,
}

const UHandleRouteWithChildren =
  UHandleRoute._addFileChildren(UHandleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  UHandleRoute: UHandleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
